In [3]:
from vnstock import Vnstock

stock = Vnstock().stock(symbol="FPT", source='TCBS')
finance = stock.finance
income_statement = finance.income_statement(period='quarter').reset_index()

2025-06-27 12:06:30 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

In [15]:
from vnstock import Vnstock
def load_company_info(ticker: str):
    stock = Vnstock().stock(symbol=ticker, source='TCBS')
    company = stock.company

    overview = company.overview()
    # overview['website'] = overview['website'].removeprefix(
    #     'https://').removeprefix('http://')

    shareholders_df = company.shareholders()
    shareholders_df["share_own_percent"] = (
        shareholders_df["share_own_percent"] * 100).round(2)

    shareholders = shareholders_df.to_dict("records")
    events = company.events()
    events['price_change_ratio'] = (events['price_change_ratio']*100).round(2)
    events = events.to_dict("records")

    news = company.news()
    news = news[~news['title'].str.contains('insider', case=False, na=False)]
    news['price_change_ratio'] = (news['price_change_ratio']*100).round(2)
    news = news.to_dict("records")

    return overview, shareholders, events, news

In [16]:
overview, shareholders, processed_events, news = load_company_info('FPT')
overview

2025-06-27 14:19:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

  symbol exchange  ... industry_id industry_id_v2
0    FPT     HOSE  ...         310           9537

[1 rows x 18 columns]

In [20]:
from vnstock import Vnstock
company = Vnstock().stock(symbol='FPT', source='TCBS').company
df = company.profile()
print(df.loc[0, 'key_developments'])  # or any other long field

2025-06-27 12:50:04 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

 1.      Technology  Digital transformation based on technologies: AI, RPA, IoT, BigData, Cloud,…  Specialized solutions in fields: Banking - Finance, Public Finance, Telecommunication, Healthcare, Transport, Electricity, Water, Gas,…  Technological system integration and transformation.  Solution based on technology platforms: SAP, Oracle, Microsoft, ESRI.  Software testing and quality assurance services.  Microcircuit design, embedded software manufacturing, CAD/CAE…  2.      Telecommunication  Telecommunication services: Internet, exclusively leased line, data center, VoIP phone, value-added services, international and interprovincial connection, Cloud and IoT services… FPT television services: FPT television, FPT Play, Internet and mobile platform-based entertainment services. Digital content services: digital newspapers including VnExpress.net, Ngoisao.net, iOne.net, online advertisement, eClick AdNetwork smart advertising system.   3. Education  Elementary, secondary and highschool education and training.  Vocational, undergraduate and post-graduate education. International affiliate programs and international student development programs.  Training programs for enterprises.  Online university.

In [8]:
df

,symbol,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies
0,VCB,Joint Stock Commercial Bank For Foreign Trade ...,Joint Stock Commercial Bank For Foreign Trade...,"October 30, 1962: Bank for Foreign Trade of ...",None,Risks related to geopolitical instability and...,Account service Mobilizing capital service; ...,"As the leading bank in Vietnam, one of the..."

In [1]:
import pandas as pd
import time
from tqdm import tqdm
from vnstock import Vnstock, Screener

def load_tickers(checkpoint_path="tickers_progress.csv",
                 checkpoint_every=10,
                 sleep_between=1.0):
    # 1) pull initial universe
    screener = Screener(source="TCBS")
    df0 = screener.stock(
        {"exchangeName": "HOSE,HNX", "marketCap": (2_000, 9_999_999_999_999)},
        limit=1700,
        lang="en"
    )
    tickers = df0["ticker"].tolist()

    # 2) try to resume from existing checkpoint, if present
    try:
        done_df = pd.read_csv(checkpoint_path)
        done_set = set(done_df["ticker"].tolist())
        results = done_df.to_dict(orient="records")
        start_idx = len(results)
        print(f"Resuming from {checkpoint_path}, {start_idx} tickers already done.")
    except FileNotFoundError:
        results = []
        done_set = set()
        start_idx = 0
        print("No checkpoint found—starting fresh.")

    # 3) iterate, fetch company info for each ticker
    for i, ticker in enumerate(tqdm(tickers[start_idx:], 
                                   desc="Fetching tickers", 
                                   unit="stk"), start=start_idx):
        if ticker in done_set:
            continue

        try:
            stock = Vnstock().stock(symbol=ticker, source="TCBS")
            company = stock.company

            # pull profile & overview
            prof = company.profile().iloc[0]
            over = company.overview().iloc[0]

            results.append({
                "ticker": ticker,
                "name": prof["company_name"],
                "short_name": over["short_name"]
            })
            done_set.add(ticker)

        except Exception as e:
            print(f"[{ticker}] ERROR: {e} — skipping")

        # checkpoint every N
        if (i + 1) % checkpoint_every == 0:
            pd.DataFrame(results).to_csv(checkpoint_path, index=False)
            print(f"Checkpoint: saved {len(results)} rows to {checkpoint_path}")

        # simple rate-limit throttle
        time.sleep(sleep_between)

    # final save
    out_df = pd.DataFrame(results)
    out_df.to_csv(checkpoint_path, index=False)
    return out_df

In [2]:
load_tickers()

No checkpoint found—starting fresh.

Fetching tickers:   0%|          | 0/210 [00:00<?, ?stk/s]2025-06-27 14:32:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   0%|          | 1/210 [00:02<08:22,  2.40s/stk]2025-06-27 14:32:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   1%|          | 2/210 [00:04<08:01,  2.31s/stk]2025-06-27 14:32:57 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   1%|▏         | 3/210 [00:06<07:53,  2.29s/stk]2025-06-27 14:32:59 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   2%|▏         | 4/210 [00:09<07:46,  2.27s/stk]2025-06-27 14:33:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   2%|▏         | 5/210 [00:11<07:52,  2.30s/stk]2025-06-27 14:33:04 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   3%|▎         | 6/210 [00:13<07:46,  2.29s/stk]2025-06-27 14:33:06 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   3%|▎         | 7/210 [00:16<07:49,  2.31s/stk]2025-06-27 14:33:09 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   4%|▍         | 8/210 [00:18<07:55,  2.35s/stk]2025-06-27 14:33:11 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   4%|▍         | 9/210 [00:20<07:45,  2.32s/stk]2025-06-27 14:33:13 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 10 rows to tickers_progress.csv

Fetching tickers:   5%|▍         | 10/210 [00:23<07:41,  2.31s/stk]2025-06-27 14:33:16 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   5%|▌         | 11/210 [00:25<07:40,  2.32s/stk]2025-06-27 14:33:18 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   6%|▌         | 12/210 [00:27<07:35,  2.30s/stk]2025-06-27 14:33:20 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   6%|▌         | 13/210 [00:30<07:36,  2.32s/stk]2025-06-27 14:33:23 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   7%|▋         | 14/210 [00:32<07:41,  2.35s/stk]2025-06-27 14:33:25 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   7%|▋         | 15/210 [00:34<07:34,  2.33s/stk]2025-06-27 14:33:27 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   8%|▊         | 16/210 [00:37<07:33,  2.34s/stk]2025-06-27 14:33:30 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   8%|▊         | 17/210 [00:39<07:27,  2.32s/stk]2025-06-27 14:33:32 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   9%|▊         | 18/210 [00:41<07:26,  2.32s/stk]2025-06-27 14:33:34 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:   9%|▉         | 19/210 [00:44<07:25,  2.33s/stk]2025-06-27 14:33:37 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 20 rows to tickers_progress.csv

Fetching tickers:  10%|▉         | 20/210 [00:46<07:23,  2.33s/stk]2025-06-27 14:33:39 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  10%|█         | 21/210 [00:48<07:17,  2.31s/stk]2025-06-27 14:33:41 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  10%|█         | 22/210 [00:51<07:16,  2.32s/stk]2025-06-27 14:33:44 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  11%|█         | 23/210 [00:53<07:17,  2.34s/stk]2025-06-27 14:33:46 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  11%|█▏        | 24/210 [00:55<07:21,  2.37s/stk]2025-06-27 14:33:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  12%|█▏        | 25/210 [00:58<07:23,  2.40s/stk]2025-06-27 14:33:51 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  12%|█▏        | 26/210 [01:00<07:19,  2.39s/stk]2025-06-27 14:33:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  13%|█▎        | 27/210 [01:03<07:20,  2.41s/stk]2025-06-27 14:33:56 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  13%|█▎        | 28/210 [01:05<07:09,  2.36s/stk]2025-06-27 14:33:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  14%|█▍        | 29/210 [01:07<07:01,  2.33s/stk]2025-06-27 14:34:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 30 rows to tickers_progress.csv

Fetching tickers:  14%|█▍        | 30/210 [01:10<07:06,  2.37s/stk]2025-06-27 14:34:03 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  15%|█▍        | 31/210 [01:12<07:08,  2.39s/stk]2025-06-27 14:34:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  15%|█▌        | 32/210 [01:15<07:09,  2.41s/stk]2025-06-27 14:34:08 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  16%|█▌        | 33/210 [01:17<07:09,  2.43s/stk]2025-06-27 14:34:10 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  16%|█▌        | 34/210 [01:19<06:57,  2.37s/stk]2025-06-27 14:34:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  17%|█▋        | 35/210 [01:22<06:54,  2.37s/stk]2025-06-27 14:34:15 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  17%|█▋        | 36/210 [01:24<06:51,  2.37s/stk]2025-06-27 14:34:17 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  18%|█▊        | 37/210 [01:26<06:53,  2.39s/stk]2025-06-27 14:34:19 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  18%|█▊        | 38/210 [01:29<06:54,  2.41s/stk]2025-06-27 14:34:22 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  19%|█▊        | 39/210 [01:31<06:44,  2.36s/stk]2025-06-27 14:34:24 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 40 rows to tickers_progress.csv

Fetching tickers:  19%|█▉        | 40/210 [01:33<06:41,  2.36s/stk]2025-06-27 14:34:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  20%|█▉        | 41/210 [01:36<06:38,  2.36s/stk]2025-06-27 14:34:29 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  20%|██        | 42/210 [01:38<06:36,  2.36s/stk]2025-06-27 14:34:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  20%|██        | 43/210 [01:41<06:38,  2.39s/stk]2025-06-27 14:34:34 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  21%|██        | 44/210 [01:43<06:39,  2.41s/stk]2025-06-27 14:34:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  21%|██▏       | 45/210 [01:46<06:39,  2.42s/stk]2025-06-27 14:34:39 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  22%|██▏       | 46/210 [01:48<06:34,  2.41s/stk]2025-06-27 14:34:41 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  22%|██▏       | 47/210 [01:50<06:29,  2.39s/stk]2025-06-27 14:34:43 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  23%|██▎       | 48/210 [01:53<06:30,  2.41s/stk]2025-06-27 14:34:46 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  23%|██▎       | 49/210 [01:55<06:20,  2.36s/stk]2025-06-27 14:34:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 50 rows to tickers_progress.csv

Fetching tickers:  24%|██▍       | 50/210 [01:57<06:17,  2.36s/stk]2025-06-27 14:34:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  24%|██▍       | 51/210 [02:00<06:15,  2.36s/stk]2025-06-27 14:34:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  25%|██▍       | 52/210 [02:02<06:12,  2.36s/stk]2025-06-27 14:34:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  25%|██▌       | 53/210 [02:04<06:14,  2.39s/stk]2025-06-27 14:34:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  26%|██▌       | 54/210 [02:07<06:16,  2.41s/stk]2025-06-27 14:35:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  26%|██▌       | 55/210 [02:09<06:15,  2.42s/stk]2025-06-27 14:35:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  27%|██▋       | 56/210 [02:12<06:14,  2.43s/stk]2025-06-27 14:35:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  27%|██▋       | 57/210 [02:14<06:03,  2.38s/stk]2025-06-27 14:35:07 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  28%|██▊       | 58/210 [02:16<06:00,  2.37s/stk]2025-06-27 14:35:09 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  28%|██▊       | 59/210 [02:19<05:57,  2.37s/stk]2025-06-27 14:35:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 60 rows to tickers_progress.csv

Fetching tickers:  29%|██▊       | 60/210 [02:21<05:54,  2.36s/stk]2025-06-27 14:35:14 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  29%|██▉       | 61/210 [02:24<05:52,  2.36s/stk]2025-06-27 14:35:17 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  30%|██▉       | 62/210 [02:26<05:53,  2.39s/stk]2025-06-27 14:35:19 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  30%|███       | 63/210 [02:28<05:54,  2.41s/stk]2025-06-27 14:35:21 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  30%|███       | 64/210 [02:31<05:53,  2.42s/stk]2025-06-27 14:35:24 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  31%|███       | 65/210 [02:33<05:51,  2.43s/stk]2025-06-27 14:35:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  31%|███▏      | 66/210 [02:36<05:47,  2.41s/stk]2025-06-27 14:35:29 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  32%|███▏      | 67/210 [02:38<05:44,  2.41s/stk]2025-06-27 14:35:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  32%|███▏      | 68/210 [02:41<05:42,  2.41s/stk]2025-06-27 14:35:34 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  33%|███▎      | 69/210 [02:43<05:41,  2.42s/stk]2025-06-27 14:35:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 70 rows to tickers_progress.csv

Fetching tickers:  33%|███▎      | 70/210 [02:45<05:31,  2.37s/stk]2025-06-27 14:35:38 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  34%|███▍      | 71/210 [02:48<05:29,  2.37s/stk]2025-06-27 14:35:41 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  34%|███▍      | 72/210 [02:50<05:26,  2.37s/stk]2025-06-27 14:35:43 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  35%|███▍      | 73/210 [02:52<05:27,  2.39s/stk]2025-06-27 14:35:45 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  35%|███▌      | 74/210 [02:55<05:23,  2.38s/stk]2025-06-27 14:35:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  36%|███▌      | 75/210 [02:57<05:20,  2.37s/stk]2025-06-27 14:35:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  36%|███▌      | 76/210 [03:00<05:21,  2.40s/stk]2025-06-27 14:35:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  37%|███▋      | 77/210 [03:02<05:21,  2.42s/stk]2025-06-27 14:35:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  37%|███▋      | 78/210 [03:04<05:20,  2.43s/stk]2025-06-27 14:35:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  38%|███▊      | 79/210 [03:07<05:19,  2.44s/stk]2025-06-27 14:36:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 80 rows to tickers_progress.csv

Fetching tickers:  38%|███▊      | 80/210 [03:09<05:18,  2.45s/stk]2025-06-27 14:36:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  39%|███▊      | 81/210 [03:12<05:11,  2.42s/stk]2025-06-27 14:36:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  39%|███▉      | 82/210 [03:14<05:06,  2.40s/stk]2025-06-27 14:36:07 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  40%|███▉      | 83/210 [03:17<05:06,  2.42s/stk]2025-06-27 14:36:10 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  40%|████      | 84/210 [03:19<05:02,  2.40s/stk]2025-06-27 14:36:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  40%|████      | 85/210 [03:21<05:02,  2.42s/stk]2025-06-27 14:36:14 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  41%|████      | 86/210 [03:24<05:01,  2.43s/stk]2025-06-27 14:36:17 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  41%|████▏     | 87/210 [03:26<04:52,  2.37s/stk]2025-06-27 14:36:19 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  42%|████▏     | 88/210 [03:28<04:48,  2.37s/stk]2025-06-27 14:36:21 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  42%|████▏     | 89/210 [03:31<04:49,  2.40s/stk]2025-06-27 14:36:24 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 90 rows to tickers_progress.csv

Fetching tickers:  43%|████▎     | 90/210 [03:33<04:45,  2.38s/stk]2025-06-27 14:36:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  43%|████▎     | 91/210 [03:36<04:42,  2.37s/stk]2025-06-27 14:36:29 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  44%|████▍     | 92/210 [03:38<04:43,  2.40s/stk]2025-06-27 14:36:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  44%|████▍     | 93/210 [03:41<04:42,  2.42s/stk]2025-06-27 14:36:34 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  45%|████▍     | 94/210 [03:43<04:41,  2.43s/stk]2025-06-27 14:36:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  45%|████▌     | 95/210 [03:46<04:44,  2.47s/stk]2025-06-27 14:36:39 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  46%|████▌     | 96/210 [03:48<04:44,  2.49s/stk]2025-06-27 14:36:41 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  46%|████▌     | 97/210 [03:51<04:40,  2.49s/stk]2025-06-27 14:36:44 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  47%|████▋     | 98/210 [03:53<04:37,  2.48s/stk]2025-06-27 14:36:46 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  47%|████▋     | 99/210 [03:55<04:27,  2.41s/stk]2025-06-27 14:36:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 100 rows to tickers_progress.csv

Fetching tickers:  48%|████▊     | 100/210 [03:58<04:23,  2.39s/stk]2025-06-27 14:36:51 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  48%|████▊     | 101/210 [04:00<04:16,  2.35s/stk]2025-06-27 14:36:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  49%|████▊     | 102/210 [04:02<04:14,  2.35s/stk]2025-06-27 14:36:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  49%|████▉     | 103/210 [04:05<04:15,  2.39s/stk]2025-06-27 14:36:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  50%|████▉     | 104/210 [04:07<04:11,  2.37s/stk]2025-06-27 14:37:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  50%|█████     | 105/210 [04:09<04:05,  2.34s/stk]2025-06-27 14:37:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  50%|█████     | 106/210 [04:12<04:07,  2.38s/stk]2025-06-27 14:37:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  51%|█████     | 107/210 [04:14<04:03,  2.36s/stk]2025-06-27 14:37:07 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  51%|█████▏    | 108/210 [04:16<04:01,  2.36s/stk]2025-06-27 14:37:10 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  52%|█████▏    | 109/210 [04:19<03:58,  2.36s/stk]2025-06-27 14:37:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 110 rows to tickers_progress.csv

Fetching tickers:  52%|█████▏    | 110/210 [04:21<03:55,  2.36s/stk]2025-06-27 14:37:14 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  53%|█████▎    | 111/210 [04:24<03:52,  2.35s/stk]2025-06-27 14:37:17 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  53%|█████▎    | 112/210 [04:26<03:48,  2.33s/stk]2025-06-27 14:37:19 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  54%|█████▍    | 113/210 [04:28<03:46,  2.34s/stk]2025-06-27 14:37:21 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  54%|█████▍    | 114/210 [04:31<03:47,  2.37s/stk]2025-06-27 14:37:24 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  55%|█████▍    | 115/210 [04:33<03:44,  2.37s/stk]2025-06-27 14:37:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  55%|█████▌    | 116/210 [04:35<03:39,  2.33s/stk]2025-06-27 14:37:28 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  56%|█████▌    | 117/210 [04:38<03:40,  2.37s/stk]2025-06-27 14:37:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  56%|█████▌    | 118/210 [04:40<03:37,  2.37s/stk]2025-06-27 14:37:33 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  57%|█████▋    | 119/210 [04:42<03:37,  2.39s/stk]2025-06-27 14:37:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 120 rows to tickers_progress.csv

Fetching tickers:  57%|█████▋    | 120/210 [04:45<03:34,  2.38s/stk]2025-06-27 14:37:38 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  58%|█████▊    | 121/210 [04:47<03:28,  2.34s/stk]2025-06-27 14:37:40 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  58%|█████▊    | 122/210 [04:49<03:26,  2.35s/stk]2025-06-27 14:37:42 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  59%|█████▊    | 123/210 [04:52<03:26,  2.38s/stk]2025-06-27 14:37:45 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  59%|█████▉    | 124/210 [04:54<03:21,  2.34s/stk]2025-06-27 14:37:47 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  60%|█████▉    | 125/210 [04:57<03:19,  2.35s/stk]2025-06-27 14:37:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  60%|██████    | 126/210 [04:59<03:19,  2.38s/stk]2025-06-27 14:37:52 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  60%|██████    | 127/210 [05:01<03:17,  2.38s/stk]2025-06-27 14:37:54 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  61%|██████    | 128/210 [05:04<03:16,  2.40s/stk]2025-06-27 14:37:57 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  61%|██████▏   | 129/210 [05:06<03:12,  2.38s/stk]2025-06-27 14:37:59 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 130 rows to tickers_progress.csv

Fetching tickers:  62%|██████▏   | 130/210 [05:09<03:12,  2.41s/stk]2025-06-27 14:38:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  62%|██████▏   | 131/210 [05:11<03:08,  2.39s/stk]2025-06-27 14:38:04 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  63%|██████▎   | 132/210 [05:13<03:05,  2.38s/stk]2025-06-27 14:38:06 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  63%|██████▎   | 133/210 [05:16<03:04,  2.40s/stk]2025-06-27 14:38:09 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  64%|██████▍   | 134/210 [05:18<03:01,  2.39s/stk]2025-06-27 14:38:11 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  64%|██████▍   | 135/210 [05:21<03:00,  2.41s/stk]2025-06-27 14:38:14 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  65%|██████▍   | 136/210 [05:23<02:56,  2.39s/stk]2025-06-27 14:38:16 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  65%|██████▌   | 137/210 [05:25<02:54,  2.38s/stk]2025-06-27 14:38:18 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  66%|██████▌   | 138/210 [05:28<02:52,  2.40s/stk]2025-06-27 14:38:21 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  66%|██████▌   | 139/210 [05:30<02:49,  2.39s/stk]2025-06-27 14:38:23 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 140 rows to tickers_progress.csv

Fetching tickers:  67%|██████▋   | 140/210 [05:33<02:50,  2.44s/stk]2025-06-27 14:38:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  67%|██████▋   | 141/210 [05:35<02:46,  2.41s/stk]2025-06-27 14:38:28 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  68%|██████▊   | 142/210 [05:37<02:45,  2.43s/stk]2025-06-27 14:38:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  68%|██████▊   | 143/210 [05:40<02:43,  2.44s/stk]2025-06-27 14:38:33 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  69%|██████▊   | 144/210 [05:42<02:41,  2.44s/stk]2025-06-27 14:38:35 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  69%|██████▉   | 145/210 [05:45<02:39,  2.45s/stk]2025-06-27 14:38:38 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  70%|██████▉   | 146/210 [05:47<02:36,  2.45s/stk]2025-06-27 14:38:40 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  70%|███████   | 147/210 [05:50<02:34,  2.45s/stk]2025-06-27 14:38:43 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  70%|███████   | 148/210 [05:52<02:28,  2.39s/stk]2025-06-27 14:38:45 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  71%|███████   | 149/210 [05:54<02:25,  2.38s/stk]2025-06-27 14:38:47 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 150 rows to tickers_progress.csv

Fetching tickers:  71%|███████▏  | 150/210 [05:57<02:22,  2.37s/stk]2025-06-27 14:38:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  72%|███████▏  | 151/210 [05:59<02:19,  2.37s/stk]2025-06-27 14:38:52 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  72%|███████▏  | 152/210 [06:02<02:18,  2.39s/stk]2025-06-27 14:38:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  73%|███████▎  | 153/210 [06:04<02:15,  2.38s/stk]2025-06-27 14:38:57 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  73%|███████▎  | 154/210 [06:06<02:13,  2.38s/stk]2025-06-27 14:38:59 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  74%|███████▍  | 155/210 [06:08<02:08,  2.34s/stk]2025-06-27 14:39:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  74%|███████▍  | 156/210 [06:11<02:08,  2.37s/stk]2025-06-27 14:39:04 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  75%|███████▍  | 157/210 [06:13<02:07,  2.40s/stk]2025-06-27 14:39:06 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  75%|███████▌  | 158/210 [06:16<02:02,  2.36s/stk]2025-06-27 14:39:09 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  76%|███████▌  | 159/210 [06:18<02:00,  2.36s/stk]2025-06-27 14:39:11 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 160 rows to tickers_progress.csv

Fetching tickers:  76%|███████▌  | 160/210 [06:20<01:59,  2.39s/stk]2025-06-27 14:39:14 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  77%|███████▋  | 161/210 [06:23<01:56,  2.38s/stk]2025-06-27 14:39:16 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  77%|███████▋  | 162/210 [06:25<01:53,  2.37s/stk]2025-06-27 14:39:18 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  78%|███████▊  | 163/210 [06:28<01:52,  2.40s/stk]2025-06-27 14:39:21 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  78%|███████▊  | 164/210 [06:30<01:49,  2.38s/stk]2025-06-27 14:39:23 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  79%|███████▊  | 165/210 [06:32<01:46,  2.38s/stk]2025-06-27 14:39:25 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  79%|███████▉  | 166/210 [06:35<01:44,  2.37s/stk]2025-06-27 14:39:28 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  80%|███████▉  | 167/210 [06:38<01:48,  2.52s/stk]2025-06-27 14:39:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  80%|████████  | 168/210 [06:40<01:44,  2.50s/stk]2025-06-27 14:39:33 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  80%|████████  | 169/210 [06:42<01:41,  2.49s/stk]2025-06-27 14:39:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 170 rows to tickers_progress.csv

Fetching tickers:  81%|████████  | 170/210 [06:45<01:39,  2.48s/stk]2025-06-27 14:39:38 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  81%|████████▏ | 171/210 [06:47<01:35,  2.44s/stk]2025-06-27 14:39:40 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  82%|████████▏ | 172/210 [06:50<01:35,  2.51s/stk]2025-06-27 14:39:43 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  82%|████████▏ | 173/210 [06:53<01:33,  2.52s/stk]2025-06-27 14:39:46 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  83%|████████▎ | 174/210 [06:55<01:30,  2.50s/stk]2025-06-27 14:39:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  83%|████████▎ | 175/210 [06:57<01:27,  2.49s/stk]2025-06-27 14:39:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  84%|████████▍ | 176/210 [07:00<01:22,  2.42s/stk]2025-06-27 14:39:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  84%|████████▍ | 177/210 [07:02<01:21,  2.46s/stk]2025-06-27 14:39:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  85%|████████▍ | 178/210 [07:05<01:18,  2.46s/stk]2025-06-27 14:39:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  85%|████████▌ | 179/210 [07:07<01:15,  2.43s/stk]2025-06-27 14:40:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 180 rows to tickers_progress.csv

Fetching tickers:  86%|████████▌ | 180/210 [07:10<01:13,  2.44s/stk]2025-06-27 14:40:03 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  86%|████████▌ | 181/210 [07:12<01:10,  2.42s/stk]2025-06-27 14:40:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  87%|████████▋ | 182/210 [07:14<01:07,  2.42s/stk]2025-06-27 14:40:07 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  87%|████████▋ | 183/210 [07:17<01:05,  2.41s/stk]2025-06-27 14:40:10 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  88%|████████▊ | 184/210 [07:19<01:02,  2.39s/stk]2025-06-27 14:40:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  88%|████████▊ | 185/210 [07:22<01:00,  2.41s/stk]2025-06-27 14:40:15 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  89%|████████▊ | 186/210 [07:24<00:57,  2.39s/stk]2025-06-27 14:40:17 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  89%|████████▉ | 187/210 [07:26<00:54,  2.38s/stk]2025-06-27 14:40:19 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  90%|████████▉ | 188/210 [07:29<00:52,  2.37s/stk]2025-06-27 14:40:22 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  90%|█████████ | 189/210 [07:31<00:49,  2.37s/stk]2025-06-27 14:40:24 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 190 rows to tickers_progress.csv

Fetching tickers:  90%|█████████ | 190/210 [07:33<00:47,  2.40s/stk]2025-06-27 14:40:26 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  91%|█████████ | 191/210 [07:36<00:45,  2.38s/stk]2025-06-27 14:40:29 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  91%|█████████▏| 192/210 [07:38<00:43,  2.41s/stk]2025-06-27 14:40:31 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  92%|█████████▏| 193/210 [07:41<00:40,  2.39s/stk]2025-06-27 14:40:34 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  92%|█████████▏| 194/210 [07:43<00:38,  2.41s/stk]2025-06-27 14:40:36 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  93%|█████████▎| 195/210 [07:45<00:35,  2.36s/stk]2025-06-27 14:40:38 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  93%|█████████▎| 196/210 [07:48<00:33,  2.39s/stk]2025-06-27 14:40:41 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  94%|█████████▍| 197/210 [07:50<00:30,  2.38s/stk]2025-06-27 14:40:43 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  94%|█████████▍| 198/210 [07:52<00:28,  2.34s/stk]2025-06-27 14:40:45 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  95%|█████████▍| 199/210 [07:55<00:26,  2.41s/stk]2025-06-27 14:40:48 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 200 rows to tickers_progress.csv

Fetching tickers:  95%|█████████▌| 200/210 [07:57<00:23,  2.39s/stk]2025-06-27 14:40:50 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  96%|█████████▌| 201/210 [08:00<00:21,  2.38s/stk]2025-06-27 14:40:53 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  96%|█████████▌| 202/210 [08:02<00:19,  2.40s/stk]2025-06-27 14:40:55 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  97%|█████████▋| 203/210 [08:05<00:16,  2.42s/stk]2025-06-27 14:40:58 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  97%|█████████▋| 204/210 [08:07<00:14,  2.43s/stk]2025-06-27 14:41:00 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  98%|█████████▊| 205/210 [08:09<00:12,  2.41s/stk]2025-06-27 14:41:02 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  98%|█████████▊| 206/210 [08:12<00:09,  2.39s/stk]2025-06-27 14:41:05 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  99%|█████████▊| 207/210 [08:14<00:07,  2.39s/stk]2025-06-27 14:41:07 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers:  99%|█████████▉| 208/210 [08:17<00:04,  2.40s/stk]2025-06-27 14:41:10 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.
Fetching tickers: 100%|█████████▉| 209/210 [08:19<00:02,  2.39s/stk]2025-06-27 14:41:12 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

Checkpoint: saved 210 rows to tickers_progress.csv

Fetching tickers: 100%|██████████| 210/210 [08:21<00:00,  2.39s/stk]

,ticker,name,short_name
0,AAA,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics
1,ACB,Asia Commercial Joint Stock Bank,Asia Commercial Bank
2,ACG,An Cuong Wood - Working Joint Stock Company,An Cuong Wood
3,AGG,An Gia Real Estate Investment And Development ...,An Gia Real Estate
4,AGR,AgriBank Securities Corporation,AgriBank Securities
...,...,...,...
205,VRE,Vincom Retail Joint Stock Company,Vincom Retail
206,VSC,Viet Nam Container Shipping Joint Stock Company,Vietnam Container Shipping
207,VSH,Vinh Son - Song Hinh Hydropower Joint Stock Co...,Vinh Son - Song Hinh Hydropower
208,VTP,Viettel Post Joint Stock Corporation,Viettel Post
209,YEG,Yeah1 Group Corporation,Yeah1 Group